# Generated by Django 5.2.6 on 2025-09-24 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва кафедри')),
                ('head', models.CharField(max_length=200, verbose_name='Завідувач кафедри')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва спеціальності')),
                ('code', models.CharField(max_length=20, verbose_name='Код спеціальності')),
                ('description', models.TextField(verbose_name='Опис')),
                ('coordinator_name', models.CharField(max_length=200, verbose_name='Імʼя координатора')),
                ('coordinator_contact', models.CharField(max_length=200, verbose_name='Контакт координатора')),
                ('disciplines', models.TextField(help_text='Список дисциплін через кому', verbose_name='Дисципліни')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='main.department', verbose_name='Випускова кафедра')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Імʼя викладача')),
                ('position', models.CharField(max_length=200, verbose_name='Посада')),
                ('degree', models.CharField(max_length=200, verbose_name='Науковий ступінь')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='main.department', verbose_name='Кафедра')),
            ],
        ),
    ]
