# Generated by Django 5.2.6 on 2025-09-24 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст головної сторінки')),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='main.department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Імʼя'),
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва спеціальності')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('description', models.TextField(verbose_name='Опис')),
                ('coordinator_name', models.CharField(max_length=200, verbose_name='Імʼя координатора')),
                ('coordinator_contact', models.CharField(max_length=200, verbose_name='Контакт координатора')),
                ('disciplines', models.TextField(verbose_name='Список дисциплін')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='main.department')),
            ],
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
