# Generated by Django 5.2.6 on 2025-09-28 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homepage_alter_teacher_department_alter_teacher_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
        migrations.RemoveField(
            model_name='department',
            name='head',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='code',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='coordinator_contact',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='coordinator_name',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='description',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='disciplines',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='position',
        ),
        migrations.AddField(
            model_name='teacher',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.specialty'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
