# Generated by Django 5.2.6 on 2025-09-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_teacher_specialty_department_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='coordinator_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='coordinator_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='disciplines',
            field=models.TextField(blank=True, null=True),
        ),
    ]
