# Generated by Django 5.2.6 on 2025-09-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_specialty_code_specialty_coordinator_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='coordinator_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
